# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Federico Brancasi <fbrancasi@ethz.ch>

name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./brevitexporter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Build Package
        run: |
          pip install build
          python -m build --sdist --wheel .

  test-mnist:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./brevitexporter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run MNIST Test
        run: |
          python -m pytest -v -s src/brevitexporter/tests/test_mnist.py

  test-resnet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./brevitexporter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run ResNet Test
        run: |
          python -m pytest -v -s src/brevitexporter/tests/test_resnet18.py

  test-simple-cnn:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./brevitexporter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Simple CNN Test
        run: |
          python -m pytest -v -s src/brevitexporter/tests/test_simple_cnn.py

  test-simple-mha:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./brevitexporter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Simple MHA Test
        run: |
          python -m pytest -v -s src/brevitexporter/tests/test_simple_mha.py

  test-simple-nn:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./brevitexporter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Simple NN Test
        run: |
          python -m pytest -v -s src/brevitexporter/tests/test_simple_nn.py
