# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Philip Wiese <wiesep@iis.ee.ethz.ch>

name: lint

on: [ push, pull_request ]

jobs:

  lint-license:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check license
      uses: pulp-platform/pulp-actions/lint-license@v2
      with:
        license: |
          Copyright (\d{4}(-\d{4})?\s)?.*
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
        exclude_paths: |
          parsers/**/*.py

  ling-py:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Python with black
      uses: rickstaa/action-black@v1
      with:
        black_args: ". --check"
